apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mynamespace

resources:
  - ../../base


secretGenerator:
  - name: mysecrets
    type: Opaque
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true
  
patches:
  - target:
      kind: Route
      name: myapplication
    patch: |-
      - op: replace
        path: /spec/host
        value: myapp.development.aws.com
  - target:
      kind: PersistentVolumeClaim
      name: myapplication
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: myothersuperfaststorage
