apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mynamespace

resources:
  - ../../base


secretGenerator:
  - name: mysecrets
    type: Opaque
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: BuildConfig
      name: myapplication
    patch: |-
      - op: replace
        path: /spec/source/git/ref
        value: master
  - target:
      kind: Route
      name: myapplication
    patch: |-
      - op: replace
        path: /spec/host
        value: myapp.production.aws.com
