apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapplication
  labels:
    name: myapplication
    version: "1.0"
    component: worker
    part-of: myapplication
    managed-by: kustomize
    owner: 7miguel7
    project: myapplication
    created-by: 7miguel7
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 7miguel7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer

